# Generated by Django 4.0.6 on 2023-11-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=50, unique=True)),
                ('imagem', models.ImageField(upload_to='imagens/')),
            ],
        ),
    ]
