# Generated by Django 4.0.6 on 2023-11-13 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='tempo_ate_proxima_mensagem',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
    ]
