# Generated by Django 4.0.6 on 2023-11-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandos', '0002_palavraimagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavraimagem',
            name='palavra',
        ),
        migrations.AddField(
            model_name='palavraimagem',
            name='nome',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
