# Generated by Django 4.0.6 on 2023-11-13 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandos', '0002_mensagem_tempo_ate_proxima_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='tempo_ate_proxima_mensagem',
        ),
    ]
