# Generated by Django 4.0.6 on 2023-11-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandos', '0003_remove_palavraimagem_palavra_palavraimagem_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='PalavraImagem',
        ),
    ]
