# Generated by Django 4.0.6 on 2023-11-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandos', '0004_item_delete_palavraimagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('imagem', models.ImageField(upload_to='imagens/')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
