# Generated by Django 4.0.6 on 2023-11-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandos', '0005_imagem_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='tipo_mensagem',
            field=models.CharField(choices=[('dica', 'Dica'), ('informacao', 'Informação')], default='informacao', max_length=20),
        ),
    ]
